### ISSUE TITLE
Проверка лабораторной работы 2

### ISSUE THREAD

**Issue by umorw** [umorw/repositumorw#1]
Работу выполнила Иванова Л.

To: @evgeny-p

**Comment by evgeny-p** [comment]
Замечания.

Форматирование кода:
1. Для отступов в коде используются [табы и пробелы одновременно](http://www.emacswiki.org/pics/static/TabsSpacesBoth.png). В результате форматирование беспорядочное, что хорошо видно [здесь](https://github.com/umorw/repositumorw/blob/9651bb211f456d5139145383bab88c537bc712c6/proga.c).
2. Неконсистентное форматирование выражений: где-то бинарные операторы выделены пробелами, где-то нет. Предпочтительнее выделять.

Нужно выбрать для себя соглашения о кодировании (некоторые ссылки были на слайдах с первой пары) и придерживаться их, следить за единообразием. В частности, следить за расстановкой пробелов: после запятых, около скобок и т. д.

Качество кода:
1. Имена переменных не соответствуют содержимому. Так, переменная `d` переиспользуется для хранения корня из дискриминанта, а переменная `a` для хранения результата выражения `2 * a`. Как следствие, формулы вычисления корней выражения выглядят некорректными. Если хочется вынести промежуточные результаты вычислений в переменные, то лучше создать новые переменные с соответствующими содержанию именами.
2. Почему-то ненулевой код завершения в случае успешного выполнения программы.

И замечание по содержанию коммита в комментарии: https://github.com/umorw/repositumorw/commit/415bfdca1b6986fdd98a40e328db5cfc163c9696

Переписывать историю для исправления последнего замечания не нужно, а все остальные стоит исправить.

**Comment by umorw** [comment]
Картинка не открывается. Почему ненулевой код завершения - понятия не имею. Без добавления -lm при компилировании программы gcc выдает ошибку про неявную функцию sqrt и что возвращает 1. math.h подключена, что ему нужно - не знаю. В всезнающем гугле говорят компилятор сменить

**Comment by evgeny-p** [comment]
> Картинка не открывается.

Ок, считаем, что ее нет. Там мемообразующий комикс о совместном использовании табов и пробелов в коде.

> Почему ненулевой код завершения - понятия не имею.

Причина ненулевого кода завершения как раз ясна: 49 строка в https://github.com/umorw/repositumorw/commit/415bfdca1b6986fdd98a40e328db5cfc163c9696. Почему она была так написана — отдельный вопрос. В общем, ожидается, что в этой строке должен быть 0.

> Без добавления -lm при компилировании программы gcc выдает ошибку про неявную функцию sqrt и что возвращает 1. math.h подключена, что ему нужно - не знаю.

Ожидаемое поведение. Реализация функции `sqrt` находится в библиотеке `libm.so`. Чтобы ее использовать, нужно линковать библиотеку к бинарнику. Ключ для линковки — `-l`, после которого следует имя библиотеки без префикса `lib` и суффикса `.so`. Т.е. результат — `-lm`. Рекомендации сменить компилятор, видимо, адресованы людям с другими проблемами.

**Comment by umorw** [comment]
При "return 0" все равно тоже самое. Возвращает 1 - поставила ему 1

**Comment by evgeny-p** [comment]
Кажется, у нас возникло недопонимание, поэтому расписываю с самого начала.

Замечание касалось строки `return 1;`. Есть соглашение, по которому приложение в случае завершения без ошибок должно возвращать в систему нулевой код. Строка `return 1;` находится как раз в той ветке кода, которая предполагает завершение без ошибок. Следовательно, в ней должно быть `return 0;`. С компиляцией это никак не связано.

**Comment by umorw** [comment]
Ок, исправила, может пару пробелов пропустила

**Comment by evgeny-p** [comment]
Исправлено далеко не все.
Если открыть [последнюю версию файла](https://github.com/umorw/repositumorw/blob/7a867a2adf5b8bcc9ee0ecd13be8c379a34eb6ca/proga.c), то можно увидеть множество мест со съехавшим форматированием.
1. В строках 11, 16, 19, 22 уровень отступов не соответствует уровню отступа всего блока.
2. Весь блок кода с 26 по 46 строку смещен на дополнительный уровень.

Включите в своем редакторе отображение пробельных символов, и станет видно, что код выровнен разными способами (горизонтальная линия — таб, точка — пробел).

![indent](https://cloud.githubusercontent.com/assets/2580154/13372960/d84f1e6a-dd7b-11e5-9af0-086f1845da77.png)

Upd: возможно, стоит заменять не табы на пробелы, а пробелы на табы. Это вопрос выбора code style и настройки редактора. Лучше один раз потратить время, чтобы потом к этому вопросу не возвращаться.

**Comment by umorw** [comment]
В mc все отступы удалила и поставила заново

**Comment by evgeny-p** [comment]
Все равно хаос, и в любом редакторе с соответствующей подсветкой это видно. Кажется, Вы действуете вслепую.

![indent2](https://cloud.githubusercontent.com/assets/2580154/13373145/d6f3bf94-dd80-11e5-9471-6f2557b55be2.png)

**Comment by umorw** [comment]
Посмотрите

**Comment by evgeny-p** [comment]
Осталось:
1. Лишние отступы в строках 17, 20, 23.
2. Нет пробелов после запятых в строке 25.

**Comment by umorw** [comment]
надеюсь, теперь все

**Comment by evgeny-p** [comment]
Принято. Задачу можно закрывать.

Предлагаю как-нибудь уделить время настройке редактора, чтобы не было необходимости контролировать форматирование вручную. Хотя бы в плане отступов.

Прикладываю гифку с поведением моего редактора без дополнительных нажатий на таб: при переводе строки отступ выбирается в соответствии с вложенностью блоков кода. Если для форматирования кода приходится прикладывать больше усилий, это повод заняться настройкой своего инструментария.

![indent](https://cloud.githubusercontent.com/assets/2580154/13373586/564179f6-dd8d-11e5-9490-50c4af6c5735.gif)

**Comment by umorw** [comment]
спасибо. попробую настроить
