### ISSUE TITLE
Проверка лабораторной работы 4

### ISSUE THREAD

**Issue by umorw** [umorw/repositumorw#2]
Выполнила Иванова Л
To: @evgeny-p

**Comment by evgeny-p** [comment]
В мейкфайле отсутствует цель для удаления артефактов сборки (объектных файлов и исполняемого файла).

**Comment by umorw** [comment]
Теперь есть

**Comment by evgeny-p** [comment]
Принято.

На будущее: чтобы не дублировать объявления функций во всех точках использования, нужно создавать заголовочные файлы.
